baseURL = 'https://syshin402.github.io/'
languageCode = 'en-us'
title = "Sophie Shin – Resume & Portfolio"
theme = "PaperMod"
enableRobotsTXT = true

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2